services:
  # Backend API service
  - type: web
    name: teachease-backend
    env: python
    buildCommand: ./backend/build.sh
    startCommand: cd backend && gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: teachease-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://teachease-frontend.onrender.com,http://localhost:5173
      - key: PYTHON_VERSION
        value: 3.11.8

  # Frontend service
  - type: web
    name: teachease-frontend
    env: node
    buildCommand: cd frontend/edu-system && npm install && npm run build
    startCommand: cd frontend/edu-system && npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_BASE_URL
        value: https://teachease-backend.onrender.com/api

# Database
databases:
  - name: teachease-db
    plan: free
